"use client";

import { useState } from "react";

const faqs = [
  {
    q: "What exactly does ShiftHire do?",
    a: "ShiftHire is an AI-powered recruitment platform that automates candidate sourcing from LinkedIn. You paste a job description, and within minutes our AI — powered by Google Gemini and Exa.ai — searches millions of LinkedIn profiles, evaluates each candidate against your requirements, and delivers a ranked shortlist with match scores and detailed reasoning. No LinkedIn Premium required.",
  },
  {
    q: "How is ShiftHire different from LinkedIn Recruiter?",
    a: "LinkedIn Recruiter requires you to manually search, filter, and evaluate every candidate yourself. ShiftHire automates the entire process end-to-end. Our AI reads your job description, generates the best possible search strategy, evaluates candidates semantically (not just by keyword), and ranks them by fit. What takes a recruiter hours takes ShiftHire under 5 minutes — at a fraction of the cost.",
  },
  {
    q: "How does the credit system work?",
    a: "Each job match costs 10 credits. You start with 100 free credits on signup — that's 10 complete job searches at no cost, no card required. Additional credits can be purchased as one-time packs or via a monthly plan. Credits never expire on paid plans.",
  },
  {
    q: "Is ShiftHire GDPR compliant?",
    a: "Yes. ShiftHire is built specifically for EMEA markets and is fully GDPR compliant. We use EU-based data infrastructure (Supabase EU region), never store personal candidate data beyond what is necessary for your search session, and do not sell or share data with third parties. Our analytics provider (Umami) is also fully anonymous and GDPR-compliant.",
  },
  {
    q: "What kind of roles can ShiftHire search for?",
    a: "Any professional role that has a presence on LinkedIn. ShiftHire is most effective for mid-to-senior level roles in technology, finance, consulting, engineering, sales, and operations. It handles multi-market and multilingual searches — ideal for EMEA-wide hiring across Germany, UK, France, Netherlands, UAE, South Africa, and beyond.",
  },
  {
    q: "How accurate are the match scores?",
    a: "Match scores are generated by Google Gemini, which evaluates each candidate's full LinkedIn profile — job history, titles, skills, location, and experience level — against your job description. In internal benchmarks, the top 5 candidates ranked by ShiftHire were considered strong fits by senior recruiters 87% of the time. Scores improve further when job descriptions are detailed.",
  },
  {
    q: "Can multiple team members use the same account?",
    a: "Currently ShiftHire operates on individual accounts. Team and enterprise plans with shared credit pools, role-based access, and collaborative shortlist review are on our roadmap. If you need a team solution immediately, contact us at enterprise@shifthire.io and we will set you up manually.",
  },
  {
    q: "How long does a job match take?",
    a: "A standard job match — searching, evaluating, and ranking up to 20 candidates — completes in 3 to 7 minutes depending on the role complexity and number of candidates requested. You can track progress in real time on your dashboard. You will be notified as soon as results are ready.",
  },
  {
    q: "Can I export candidate shortlists?",
    a: "CSV export is available on the Pro and Enterprise plans. Free plan users can view and copy candidate data directly from the results page. The export includes candidate name, LinkedIn URL, match score, match band, and the AI reasoning for each candidate.",
  },
  {
    q: "What happens if I am not satisfied with the results?",
    a: "If a job search returns zero candidates or encounters a technical failure, the credits are automatically refunded to your account. If results are poor quality, you can rerun the search with a more detailed job description — the AI performs significantly better with specific requirements, seniority levels, and location constraints included.",
  },
];

export function FaqSection() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <section className="max-w-4xl mx-auto px-6 py-24" id="faq">
      <div className="text-center mb-16">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400 text-xs font-semibold mb-6">
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          Frequently Asked Questions
        </div>
        <h2 className="text-4xl md:text-5xl font-extrabold text-white mb-4">
          Everything you need to{" "}
          <span className="bg-gradient-to-r from-amber-400 to-orange-400 bg-clip-text text-transparent">know</span>
        </h2>
        <p className="text-gray-400 text-lg max-w-xl mx-auto">
          Got questions about ShiftHire? We have got answers. If something is missing, reach us at{" "}
          <a href="mailto:hello@shifthire.io" className="text-blue-400 hover:underline">
            hello@shifthire.io
          </a>
        </p>
      </div>

      <div className="space-y-3">
        {faqs.map((faq, i) => {
          const isOpen = open === i;
          return (
            <div
              key={i}
              className={`rounded-2xl border transition-all duration-300 overflow-hidden ${
                isOpen
                  ? "bg-white/[0.05] border-blue-500/30 shadow-lg shadow-blue-500/5"
                  : "bg-white/[0.02] border-white/[0.06] hover:border-white/[0.12] hover:bg-white/[0.03]"
              }`}
            >
              <button
                className="w-full flex items-center justify-between px-6 py-5 text-left gap-4 group"
                onClick={() => setOpen(isOpen ? null : i)}
                aria-expanded={isOpen}
              >
                <span className={`text-base font-semibold transition-colors duration-200 ${isOpen ? "text-white" : "text-gray-200 group-hover:text-white"}`}>
                  {faq.q}
                </span>
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 transition-all duration-300 ${
                  isOpen
                    ? "bg-blue-600 rotate-45"
                    : "bg-white/5 group-hover:bg-white/10"
                }`}>
                  <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 4v16m8-8H4" />
                  </svg>
                </div>
              </button>

              <div
                className={`overflow-hidden transition-all duration-300 ease-in-out ${
                  isOpen ? "max-h-96 opacity-100" : "max-h-0 opacity-0"
                }`}
              >
                <div className="px-6 pb-6">
                  <div className="h-px bg-gradient-to-r from-blue-500/30 to-transparent mb-4" />
                  <p className="text-gray-400 text-sm leading-relaxed">{faq.a}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
